name: C/C++ CUDA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Required Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ wget

    - name: Manually Install libtinfo5
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/main/n/ncurses/libtinfo5_6.2-0ubuntu2_amd64.deb
        sudo dpkg -i libtinfo5_6.2-0ubuntu2_amd64.deb

    - name: Install CUDA Toolkit 11.7
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
        sudo dpkg -i cuda-keyring_1.0-1_all.deb
        sudo apt-get update
        sudo apt-get install -y cuda-toolkit-11-7

    - name: Add CUDA to PATH
      run: |
        echo "/usr/local/cuda-11.7/bin" >> $GITHUB_PATH
        echo "/usr/local/cuda-11.7/lib64" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=/usr/local/cuda-11.7/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        export PATH=/usr/local/cuda-11.7/bin:$PATH

    - name: Verify NVCC Installation
      run: nvcc --version

    - name: Compile CUDA Code
      run: nvcc -std=c++17 -o CATE *.cu *.cpp -lcudart

    - name: Run Tests
      run: ./CATE -h
